# https://github.com/crate-ci/typos#false-positives
[default]

[default.extend-identifiers]
Lik = "Lik"
missings = "missings"
incid = "incid"
CBPP = "CBPP"
livch = "livch"
studage = "studage"
lectage = "lectage"
hsz = "hsz"
uvb = "uvb"
btype = "btype"
situ = "situ"
subj = "subj"
spkr = "spkr"
prec = "prec"
mrk = "mrk"
mmec = "mmec"
insteval = "insteval"
verbagg = "verbagg"
grouseticks = "grouseticks"
dyestuff = "dyestuff"
covariate = "covariate"

[default.extend-words]
Lik = "Lik"
missings = "missings"
incid = "incid"
CBPP = "CBPP"
livch = "livch"
studage = "studage"
lectage = "lectage"
hsz = "hsz"
uvb = "uvb"
btype = "btype"
situ = "situ"
subj = "subj"
spkr = "spkr"
prec = "prec"
mrk = "mrk"
mmec = "mmec"
insteval = "insteval"
verbagg = "verbagg"
grouseticks = "grouseticks"
dyestuff = "dyestuff"
covariate = "covariate"

[type.package_toml]
# Don't check spellings in these files
extend-glob = ["Manifest.toml", "Project.toml"]
check-file = false

[type.bib]
# contain lots of names, which are a great spot for false positives
extend-glob = ["*.bib"]
check-file = false
